[2025-02-22 11:37:05,393] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: lead_scoring_data_pipeline.build_dbs scheduled__2024-11-06T00:00:00+00:00 [queued]>
[2025-02-22 11:37:05,397] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: lead_scoring_data_pipeline.build_dbs scheduled__2024-11-06T00:00:00+00:00 [queued]>
[2025-02-22 11:37:05,397] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2025-02-22 11:37:05,397] {taskinstance.py:1377} INFO - Starting attempt 1 of 2
[2025-02-22 11:37:05,398] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2025-02-22 11:37:05,414] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): build_dbs> on 2024-11-06 00:00:00+00:00
[2025-02-22 11:37:05,419] {standard_task_runner.py:52} INFO - Started process 71342 to run task
[2025-02-22 11:37:05,421] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'lead_scoring_data_pipeline', 'build_dbs', 'scheduled__2024-11-06T00:00:00+00:00', '--job-id', '1054', '--raw', '--subdir', 'DAGS_FOLDER/lead_scoring_data_pipeline.py', '--cfg-path', '/tmp/tmphu3bkpdo', '--error-file', '/tmp/tmppr5qaenu']
[2025-02-22 11:37:05,422] {standard_task_runner.py:80} INFO - Job 1054: Subtask build_dbs
[2025-02-22 11:37:05,462] {task_command.py:371} INFO - Running <TaskInstance: lead_scoring_data_pipeline.build_dbs scheduled__2024-11-06T00:00:00+00:00 [running]> on host 3766485c0f6d
[2025-02-22 11:37:05,531] {taskinstance.py:1589} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=lead_scoring_data_pipeline
AIRFLOW_CTX_TASK_ID=build_dbs
AIRFLOW_CTX_EXECUTION_DATE=2024-11-06T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-11-06T00:00:00+00:00
[2025-02-22 11:37:05,532] {logging_mixin.py:115} INFO - Initializing Database at: /workspace/Assignment/01_data_pipeline/scripts/utils_output.db
[2025-02-22 11:37:05,532] {logging_mixin.py:115} INFO - Error in database initialization: unable to open database file
[2025-02-22 11:37:05,532] {python.py:173} INFO - Done. Returned value was: None
[2025-02-22 11:37:05,537] {taskinstance.py:1415} INFO - Marking task as SUCCESS. dag_id=lead_scoring_data_pipeline, task_id=build_dbs, execution_date=20241106T000000, start_date=20250222T113705, end_date=20250222T113705
[2025-02-22 11:37:05,593] {local_task_job.py:156} INFO - Task exited with return code 0
[2025-02-22 11:37:05,640] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
