[2025-02-22 11:37:54,528] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: lead_scoring_data_pipeline.map_city_tier scheduled__2024-11-10T00:00:00+00:00 [queued]>
[2025-02-22 11:37:54,533] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: lead_scoring_data_pipeline.map_city_tier scheduled__2024-11-10T00:00:00+00:00 [queued]>
[2025-02-22 11:37:54,533] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2025-02-22 11:37:54,533] {taskinstance.py:1377} INFO - Starting attempt 1 of 2
[2025-02-22 11:37:54,533] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2025-02-22 11:37:54,551] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): map_city_tier> on 2024-11-10 00:00:00+00:00
[2025-02-22 11:37:54,556] {standard_task_runner.py:52} INFO - Started process 71889 to run task
[2025-02-22 11:37:54,558] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'lead_scoring_data_pipeline', 'map_city_tier', 'scheduled__2024-11-10T00:00:00+00:00', '--job-id', '1079', '--raw', '--subdir', 'DAGS_FOLDER/lead_scoring_data_pipeline.py', '--cfg-path', '/tmp/tmp3d9mlw1n', '--error-file', '/tmp/tmp1r8kiwgf']
[2025-02-22 11:37:54,559] {standard_task_runner.py:80} INFO - Job 1079: Subtask map_city_tier
[2025-02-22 11:37:54,600] {task_command.py:371} INFO - Running <TaskInstance: lead_scoring_data_pipeline.map_city_tier scheduled__2024-11-10T00:00:00+00:00 [running]> on host 3766485c0f6d
[2025-02-22 11:37:54,664] {taskinstance.py:1589} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=lead_scoring_data_pipeline
AIRFLOW_CTX_TASK_ID=map_city_tier
AIRFLOW_CTX_EXECUTION_DATE=2024-11-10T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-11-10T00:00:00+00:00
[2025-02-22 11:37:54,665] {logging_mixin.py:115} INFO - Using Database: /workspace/Assignment/01_data_pipeline/scripts/utils_output.db
[2025-02-22 11:37:54,665] {logging_mixin.py:115} INFO - Error in mapping city tiers: unable to open database file
[2025-02-22 11:37:54,665] {python.py:173} INFO - Done. Returned value was: None
[2025-02-22 11:37:54,670] {taskinstance.py:1415} INFO - Marking task as SUCCESS. dag_id=lead_scoring_data_pipeline, task_id=map_city_tier, execution_date=20241110T000000, start_date=20250222T113754, end_date=20250222T113754
[2025-02-22 11:37:54,730] {local_task_job.py:156} INFO - Task exited with return code 0
[2025-02-22 11:37:54,772] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
